name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build the website
        run: npm run build

      - name: Deploy the website
        uses: actions/deploy-pages@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

version: 2.1

orbs:
  node: circleci/node@5.0.0

parameters:
  build_type:
    type: enum
    enum: [debug, release]
    default: debug
  environment:
    type: enum
    enum: [staging, production]
    default: staging

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
      - run: npm run test
      - deploy:
            command: npm run deploy

workflows:
  build-and-deploy:
    when: equal: [pipeline.parameters.build_type, "release"]
    jobs:
      - build
      - deploy:
            environment: << pipeline.parameters.environment >>
