version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install
      - run: npm run test
      - deploy:
            command: npm run deploy

triggers:
  - type: push
    branches:
      - production

